apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-2
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: youremail@163.com
    privateKeySecretRef:
      name: letsencrypt-prod-2
    solvers:
    - selector: 
        dnsNames:
        - '*.yourdomain2.com'
      dns01:
        webhook:
          config:
            accessKeyId: yourAKID
            accessKeySecretRef:
              key: accessKeySecret
              name: alidns-credentials-2
            regionId: "cn-shenzhen"
            ttl: 600
          groupName: certmanager.webhook.alidns
          solverName: alidns
